export interface LoteForm {
    id_lote?: number;
    id_evento: number | string | null | undefined;
    id_proveedor: number | string | null | undefined;
    id_comprador?: number | null | undefined;
    paleta_comprador?: string | null;
    fecha_pesaje: string | Date | null | undefined;
    codigo_lote: string;
    cantidad_animales: number;
    tipo_animales: string;
    calidad_animales: string;
    peso_total: number;
    sexo: string;
    crias_hembras: number;
    crias_machos: number;
    procedencia: string;
    observaciones: string;
    puja_inicial: number;
    subastado?: number;
    incremento: number;
}

// Generated by https://quicktype.io

export interface LoteMonitor {
    lote:       LoteA | null;
    ultimaPuja: UltimaPuja | null;
}

export interface LoteA {
    id_lote:           number;
    id_evento:         number;
    id_proveedor:      number;
    id_comprador:      null;
    paleta_comprador:  null;
    fecha_pesaje:      string;
    codigo_lote:       string;
    cantidad_animales: number;
    tipo_animales:     string;
    calidad_animales:  string;
    peso_total:        string;
    sexo:              string;
    crias_hembras:     number;
    crias_machos:      number;
    procedencia:       string;
    observaciones:     string;
    puja_inicial:      string;
    puja_final:        string;
    incremento:        string;
    subastado:         number;
}

export interface UltimaPuja {
    id_puja:       number;
    id_lote:       number;
    id_usuario:    number;
    puja:          string;
    codigo_paleta: string;
    fecha_creado:  string;
    usuario:       Usuario;
}

export interface Usuario {
    nombres:        string;
    identificacion: string;
}
