// Generated by https://quicktype.io

export interface LoteEditar {
    id_lote:           number;
    id_evento:         number;
    id_proveedor:      number;
    id_comprador:      number;
    paleta_comprador:  string;
    fecha_pesaje:      string;
    codigo_lote:       string;
    cantidad_animales: number;
    tipo_animales:     string;
    calidad_animales:  string;
    peso_total:        string;
    sexo:              string;
    crias_hembras:     number;
    crias_machos:      number;
    procedencia:       string;
    observaciones:     string;
    url_video:         string;
    puja_inicial:      string;
    puja_final:        string;
    incremento:        string;
    subastado:         number;
    compradores:       Compradores;
}

interface Compradores {
    id_comprador:          number;
    codigo_paleta:         string;
    antecedentes_penales:  boolean;
    procesos_judiciales:   boolean;
    calificacion_bancaria: string;
    estado:                boolean;
    usuarioid:             number;
    usuario:               Usuario;
}

interface Usuario {
    usuarioid:      number;
    nombres:        string;
    identificacion: string;
    clave:          string;
    rol:            string;
    tipo:           number;
}
