// Generated by https://quicktype.io

export interface PujasRequest {
    pujas:        Puja[];
    mejoresPujas: Puja[];
}

export interface Puja {
    id_puja:       number;
    id_lote:       number;
    id_usuario:    number;
    puja:          string;
    codigo_paleta: string;
    fecha_creado:  string;
    usuario?:      UsuarioA;
}

export interface UsuarioA {
    nombres:        string;
    identificacion: string;
}
